version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_payload
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tamahana
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: payloaddb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

#postgresql://tamahana:admin@localhost:5432/payloaddb